-- CreateTable
CREATE TABLE "Tecnico" (
    "TEC_CODIGO" SERIAL NOT NULL,
    "TEC_NOME" TEXT NOT NULL,
    "TEC_SITUACAO" INTEGER NOT NULL,

    CONSTRAINT "Tecnico_pkey" PRIMARY KEY ("TEC_CODIGO")
);

-- CreateTable
CREATE TABLE "Cidade" (
    "CID_CODIGO" SERIAL NOT NULL,
    "CID_NOME" TEXT NOT NULL,
    "CID_CEP" TEXT,
    "CID_IBGE" TEXT NOT NULL,

    CONSTRAINT "Cidade_pkey" PRIMARY KEY ("CID_CODIGO")
);

-- CreateTable
CREATE TABLE "CTO" (
    "CTO_CODIGO" SERIAL NOT NULL,
    "TEC_CODIGO" INTEGER NOT NULL,
    "CTO_DATA" TIMESTAMP(3) NOT NULL,
    "CID_CODIGO" INTEGER NOT NULL,

    CONSTRAINT "CTO_pkey" PRIMARY KEY ("CTO_CODIGO")
);

-- AddForeignKey
ALTER TABLE "CTO" ADD CONSTRAINT "CTO_TEC_CODIGO_fkey" FOREIGN KEY ("TEC_CODIGO") REFERENCES "Tecnico"("TEC_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CTO" ADD CONSTRAINT "CTO_CID_CODIGO_fkey" FOREIGN KEY ("CID_CODIGO") REFERENCES "Cidade"("CID_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;
